---
apiVersion: v1
kind: ConfigMap
metadata:
  name: iam-token
  namespace: s3fs-ns
data:
  iam-token.sh: |
    #!/bin/bash
    eval $(/usr/bin/oidc-agent-service use>/dev/null) /usr/bin/oidc-token ${OIDC_CLIENT_NAME}

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-config
  namespace: s3fs-ns
data:
  rclone.conf: |
    [webdav]
    type = webdav
    url = https://storm-webdav-storm-webdav-ns.apps.cnsa.cr.cnaf.infn.it/indigo-dc
    vendor = other
    bearer_token_command = /tmp/iam-token.sh
