---
apiVersion: v1
kind: ConfigMap
metadata:
  name: rclone-minio-config
  namespace: rclone-ns
data:
  rclone.conf: |
    [minio]
    type = s3
    provider = INFN Cloud
    oidc_agent = true
    account = ${OIDC_CLIENT_NAME}
    env_auth = false
    access_key_id =
    secret_access_key =
    session_token =
    endpoint = https://minio-api-minio-ns.apps.cnsa.cr.cnaf.infn.it
